---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings/finalizers
  verbs:
  - get
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - compassmanagermappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymas
  verbs:
  - get
  - list
  - watch
